FROM nginx:%%NGINX_VERSION%%

# Add s6-overlay
ADD https://github.com/just-containers/s6-overlay/releases/download/v2.2.0.1/s6-overlay-amd64-installer /tmp/
RUN chmod +x /tmp/s6-overlay-amd64-installer && /tmp/s6-overlay-amd64-installer / && rm /tmp/s6-overlay-amd64-installer

ADD rootfs /

ENTRYPOINT ["/init"]
CMD ["nginx" "-g" "daemon off;"]
