name: build

on:
  push:
    branches:
      - "main"
  schedule:
    # https://crontab.guru/#40_10_*_*_*
    - cron: '40 10 * * *'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build, Tag and Push Image
      run: |
        chmod +x ./buildx.sh
        ./buildx.sh
